import Link from "next/link";
import { ArrowRight, BellRing, Check, MailCheck, MessageSquareText, Rocket, Settings2 } from "lucide-react";

import { FaqAccordion } from "@/components/faq-accordion";
import { JsonLd } from "@/components/json-ld";
import { BrowserFrame, MarketingHeading, MarketingHero } from "@/components/premium-marketing";
import { PromoVideoPlayer } from "@/components/promo-video-player";
import { CtaBand, PageShell } from "@/components/site-shell";
import { Button } from "@/components/ui/button";
import { breadcrumbJsonLd, createMetadata, faqJsonLd } from "@/lib/seo";
import { processFaqs, setup } from "@/lib/site-data";

export const metadata=createMetadata({title:"Kako deluje sistem Obrtio",description:"Od brezplačnega posveta do spletne strani in sistema za povpraševanja v 7–10 dneh.",path:"/kako-deluje",keywords:["sistem za obrtnike","izdelava spletne strani","SMS za povpraševanja"]});
export default function HowItWorksPage(){return <PageShell active="kako"><JsonLd data={[breadcrumbJsonLd([{name:"Domov",path:"/"},{name:"Kako deluje",path:"/kako-deluje"}]),faqJsonLd(processFaqs)]}/><main><MarketingHero eyebrow="Kako deluje" title="Od prvega pogovora do sistema, ki" highlight="dela za vas." text="Mi pripravimo stran, povežemo obvestila in uredimo vsebino. Vi dobite jasen pregled novih strank in se lahko posvetite delu." secondary={{label:"Poglejte pot povpraševanja",href:"#pot"}}><BrowserFrame><div className="aspect-video bg-[#EDE8F8]"><PromoVideoPlayer/></div></BrowserFrame></MarketingHero>
  <section className="px-5 py-24 md:px-8 md:py-28"><div className="mx-auto max-w-[1080px]"><MarketingHeading eyebrow="Postavitev" title="Tri jasne faze. Brez tehničnega dela za vas."/><div className="relative mt-14 grid gap-5 md:grid-cols-3">{[[MessageSquareText,"01","Spoznamo podjetje","Na kratkem posvetu zberemo storitve, območje delovanja, reference in cilje."],[Settings2,"02","Vse postavimo","Pripravimo vsebino, spletno stran, obrazce, SMS obvestila in vaš dostop."],[Rocket,"03","Začnete prejemati stranke","Po potrditvi stran objavimo, sistem pa začne zbirati povpraševanja."]].map(([Icon,n,t,d])=>{const I=Icon as typeof Rocket;return <article key={n as string} className="rounded-[24px] border border-[#E8E5EE] bg-white p-8 shadow-[0_12px_35px_rgba(28,23,46,.05)]"><div className="flex items-center justify-between"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-[#EEEAFE] text-[#6654DB]"><I size={20}/></span><span className="font-mono text-xs font-bold text-[#A09BA8]">{n as string}</span></div><h3 className="mt-7 text-xl font-extrabold">{t as string}</h3><p className="mt-3 text-sm leading-6 text-[#696470]">{d as string}</p></article>})}</div><div className="mt-8 text-center text-sm font-bold text-[#6654DB]">Običajno pripravljeno v 7–10 dneh</div></div></section>
  <section id="pot" className="bg-[#17141F] px-5 py-24 text-white md:px-8 md:py-28"><div className="mx-auto max-w-[1080px]"><MarketingHeading eyebrow="Pot povpraševanja" title="Vsaka stranka dobi odgovor. Vi dobite obvestilo." text="Sistem poskrbi za prvi odziv še preden lahko dvignete telefon." align="left"/><div className="mt-14 grid gap-4 lg:grid-cols-4">{[[MessageSquareText,"1. Oddan obrazec","Stranka jasno opiše, kaj potrebuje."],[MailCheck,"2. Potrdilo stranki","Takoj prejme profesionalno e-pošto."],[BellRing,"3. SMS izvajalcu","Vi ste o novem zanimanju obveščeni takoj."],[Check,"4. Shranjeno v sistemu","Kontakt in sporočilo sta pripravljena za odziv."]].map(([Icon,t,d])=>{const I=Icon as typeof Check;return <article key={t as string} className="rounded-[20px] border border-white/10 bg-white/5 p-6"><I size={20} className="text-[#B9B0FF]"/><h3 className="mt-5 text-sm font-extrabold">{t as string}</h3><p className="mt-2 text-xs leading-5 text-[#AAA5B4]">{d as string}</p></article>})}</div></div></section>
  <section className="px-5 py-24 md:px-8 md:py-28"><div className="mx-auto grid max-w-[1050px] items-center gap-14 lg:grid-cols-2"><div><MarketingHeading eyebrow="Vključena postavitev" title="Kaj uredimo namesto vas." text="Potrebujemo samo osnovne podatke o podjetju. Za vse ostalo poskrbi ekipa Obrtio." align="left"/><Button asChild className="mt-7"><Link href="/kontakt">Začnimo pogovor <ArrowRight size={17}/></Link></Button></div><div className="grid gap-3 sm:grid-cols-2">{setup.map(x=><div key={x} className="flex gap-3 rounded-xl border border-[#E9E7EF] bg-[#FCFBFD] p-4 text-sm font-bold"><span className="grid h-6 w-6 shrink-0 place-items-center rounded-lg bg-[#6654DB] text-white"><Check size={12}/></span>{x}</div>)}</div></div></section>
  <section className="bg-[#F7F5FC] px-5 py-24 md:px-8"><div className="mx-auto max-w-[760px]"><MarketingHeading eyebrow="Pogosta vprašanja" title="Pred začetkom je dobro vedeti."/><div className="mt-10"><FaqAccordion items={processFaqs}/></div></div></section><CtaBand title="Prvi korak traja samo 20 minut" text="Povejte nam, kako trenutno pridobivate stranke. Pokazali vam bomo konkreten naslednji korak."/></main></PageShell>}
