import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, BadgeCheck, MapPin, Search, ShieldCheck, Zap } from "lucide-react";

import { MarketingHeading } from "@/components/premium-marketing";
import { PageShell } from "@/components/site-shell";
import { Button } from "@/components/ui/button";
import { getDirectoryCompanies, getDirectoryCountries, getEnglishTradeSlug, groupByCity, trades } from "@/lib/directory";
import { createMetadata } from "@/lib/seo";

export const revalidate = 3600;
export const metadata: Metadata = createMetadata({ title: "Find local contractors", description: "Find a roofer, electrician, plumber or other local contractor and send an inquiry directly to the business.", path: "/contractors", locale: "en_US", languages: { en: "/contractors", "sl-SI": "/izvajalci", "x-default": "/contractors" } });

const tradeCopy: Record<string, { title: string; intro: string }> = { elektricar: { title: "Electricians", intro: "Electrical installations, connections, testing and repairs." }, vodovodar: { title: "Plumbers", intro: "Plumbing installations, repairs and bathroom renovations." }, krovec: { title: "Roofers", intro: "New roofs, roof replacement, repairs and sheet-metal work." }, fasader: { title: "Exterior contractors", intro: "Exterior insulation, facade work and renovations." }, "monter-klim": { title: "HVAC installers", intro: "Air-conditioning installation, servicing and maintenance." }, "toplotne-crpalke": { title: "Heat-pump installers", intro: "Heat pumps and modern heating systems." }, "soncne-elektrarne": { title: "Solar installers", intro: "Solar systems, photovoltaics and battery storage." } };

const countryLabels: Record<string, string> = { SI: "Slovenia", DE: "Germany", AT: "Austria", CH: "Switzerland", US: "United States", GB: "United Kingdom" };

export default async function ContractorsPage({ searchParams }: { searchParams: Promise<{ country?: string }> }) { const { country: requestedCountry } = await searchParams; const countries = await getDirectoryCountries(); const country = countries.includes((requestedCountry ?? "").toUpperCase()) ? requestedCountry!.toUpperCase() : (countries.includes("SI") ? "SI" : countries[0] ?? "SI"); const all = await getDirectoryCompanies(country); const byTrade = trades.map(trade => { const companies = all.filter(company => company.trade.slug === trade.slug); return { trade, count: companies.length, cities: groupByCity(companies).slice(0, 3) }; }).sort((a, b) => b.count - a.count); return <PageShell active="izvajalci" locale="en"><main>
  <section className="relative overflow-hidden bg-[#F7F5FC] px-5 py-20 md:px-8 md:py-28"><div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_0%,rgba(105,89,223,.17),transparent_45%)]"/><div className="relative mx-auto max-w-[980px] text-center"><div className="inline-flex items-center gap-2 rounded-full border border-[#DFDAF6] bg-white px-3.5 py-2 text-[12px] font-extrabold uppercase tracking-[.1em] text-[#6654DB]"><BadgeCheck size={15}/> Contractor directory</div><h1 className="mt-7 text-balance text-[43px] font-extrabold leading-[1.04] tracking-[-.047em] sm:text-[56px] md:text-[68px]">The right contractor for your project. <span className="text-[#6654DB]">No guesswork.</span></h1><p className="mx-auto mt-6 max-w-[670px] text-[17px] leading-[1.7] text-[#5D5967] md:text-[19px]">Choose a service and location. Browse local contractors and send a clear inquiry directly to a business.</p><div className="mx-auto mt-9 flex max-w-[680px] items-center gap-3 rounded-2xl border border-[#DDD8EA] bg-white p-3 shadow-[0_20px_55px_rgba(48,37,90,.12)]"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-[#EEEAFE] text-[#6654DB]"><Search size={20}/></span><div className="min-w-0 flex-1 text-left"><div className="text-xs font-bold text-[#9994A1]">What do you need?</div><div className="truncate text-sm font-extrabold sm:text-base">Choose a category below</div></div><ArrowRight className="mr-2 text-[#6654DB]"/></div></div></section>
  <section className="border-y border-[#ECEAF2] bg-white px-5 py-7 md:px-8"><div className="mx-auto flex max-w-[900px] flex-wrap justify-center gap-x-8 gap-y-3 text-[13px] font-bold text-[#55515E]">{[[ShieldCheck, "Clear contact details"], [MapPin, "Local contractors"], [Zap, "Fast inquiry"]].map(([Icon, text]) => { const I = Icon as typeof Zap; return <span key={text as string} className="flex items-center gap-2"><I size={16} className="text-[#6654DB]" />{text as string}</span>; })}</div></section>
  <section className="px-5 py-24 md:px-8 md:py-28"><div className="mx-auto max-w-[1120px]"><MarketingHeading eyebrow="Choose a service" title="Find a professional for the work you need." text={`${byTrade.length} contractor categories in ${countryLabels[country] ?? country}.`}/>{countries.length > 1 ? <div className="mt-8 flex flex-wrap justify-center gap-2">{countries.map((code) => <Link key={code} href={`/contractors?country=${code}`} className={`rounded-full border px-4 py-2 text-sm font-bold no-underline transition-colors ${code === country ? "border-[#6654DB] bg-[#6654DB] text-white" : "border-[#E4E0F4] bg-white text-[#56535F] hover:border-[#6A5AE0] hover:text-[#6A5AE0]"}`}>{countryLabels[code] ?? code}</Link>)}</div> : null}<div className="mt-14 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{byTrade.map(({ trade, count, cities }) => { const copy = tradeCopy[trade.slug] ?? { title: trade.plural, intro: trade.intro }; return <Link key={trade.slug} href={`/contractors/${getEnglishTradeSlug(trade)}?country=${country}`} className="group flex min-h-[290px] flex-col overflow-hidden rounded-[24px] border border-[#E8E5EE] bg-[#FCFBFD] p-7 no-underline shadow-[0_10px_30px_rgba(28,23,46,.04)]"><div className="flex items-start justify-between"><Image src={trade.icon} alt="" width={72} height={72} className="h-[72px] w-[72px] object-contain"/><span className="rounded-full bg-[#EEEAFE] px-3 py-1.5 text-[11px] font-extrabold text-[#6654DB]">{count} {count === 1 ? "contractor" : "contractors"}</span></div><h2 className="mt-5 text-xl font-extrabold tracking-[-.02em]">{copy.title}</h2><p className="mt-2 line-clamp-2 text-sm leading-6 text-[#67626E]">{copy.intro}</p>{cities.length ? <div className="mt-4 flex flex-wrap gap-1.5">{cities.map(city => <span key={city.citySlug} className="rounded-full border border-[#E4E1EA] bg-white px-2.5 py-1 text-[11px] font-semibold text-[#68636F]">{city.city}</span>)}</div> : null}<span className="mt-auto flex items-center gap-2 pt-5 text-sm font-extrabold text-[#6654DB]">View contractors <ArrowRight size={15} className="transition-transform group-hover:translate-x-1" /></span></Link>; })}</div></div></section>
  <section className="bg-[#17141F] px-5 py-20 text-white md:px-8"><div className="mx-auto flex max-w-[1000px] flex-col items-center justify-between gap-8 text-center md:flex-row md:text-left"><div><div className="text-xs font-extrabold uppercase tracking-[.12em] text-[#B9B0FF]">For contractors</div><h2 className="mt-3 text-[32px] font-extrabold tracking-[-.035em] md:text-[40px]">Want customers to find you here?</h2><p className="mt-3 max-w-[620px] text-[15px] leading-7 text-[#AAA5B4]">With Obrtio, you get a professional website, inquiry system and a place in the directory.</p></div><Button asChild variant="inverse" size="lg"><Link href="/contact">Join us <ArrowRight size={17}/></Link></Button></div></section>
</main></PageShell>; }
