import Link from "next/link";
import { ArrowRight, BellRing, Check, Globe2, LifeBuoy, MessageSquareText, Send, Star } from "lucide-react";

import { AddonPricingCards } from "@/components/addon-pricing-cards";
import { BrowserFrame, MarketingHeading, MarketingHero } from "@/components/premium-marketing";
import { PromoVideoPlayer } from "@/components/promo-video-player";
import { CtaBand, PageShell } from "@/components/site-shell";
import { Button } from "@/components/ui/button";
import { createMetadata } from "@/lib/seo";
import { serviceAddons } from "@/lib/site-data";

export const metadata=createMetadata({title:"Spletna stran, povpraševanja in ocene za obrtnike",description:"Spletna stran, SMS obvestila, pregled povpraševanj, Google ocene, kampanje in popolna podpora v enem sistemu.",path:"/storitve",keywords:["storitve za obrtnike","spletna stran za podjetje","sistem za povpraševanja","Google ocene"]});
const addons=serviceAddons.map(x=>({...x,unit:x.title==="Oglasi"?"kampanje":x.unit}));
const services=[[Globe2,"Profesionalna spletna stran","Do pet podstrani, prilagojenih vašim storitvam, lokaciji in strankam.",["Vsebina in slike","Mobilna izvedba","Gostovanje in vzdrževanje"]],[MessageSquareText,"Povpraševanja in stranke","Vsak nov kontakt se shrani v pregleden sistem, pripravljen za vaš odziv.",["Kontaktni obrazci","Statusi in opombe","Osnovni pregled strank"]],[BellRing,"Takojšnja obvestila","Ob novem povpraševanju vi prejmete SMS, stranka pa e-poštno potrdilo.",["SMS izvajalcu","Potrdilo stranki","Manj zamujenih priložnosti"]],[Star,"Google ocene","Po opravljenem delu stranki hitro pošljete prijazno prošnjo za Google oceno.",["SMS prošnje","Zasebne povratne informacije","Več zaupanja"]],[Send,"Akcije in priporočila","Ponovno aktivirajte obstoječe stranke in spodbudite priporočila.",["Marketinške akcije","Priporočilne akcije","Pregled rezultatov"]],[LifeBuoy,"Popolna skrb ekipe","Ni vam treba urejati strani, gostovanja ali tehničnih nastavitev.",["Spremembe vsebine","Tehnična podpora","Redno vzdrževanje"]]];

export default function ServicesPage(){return <PageShell active="storitve"><main><MarketingHero eyebrow="Vse v enem sistemu" title="Več kot spletna stran." highlight="Sistem za stranke." text="Obrtio poveže profesionalen spletni nastop, povpraševanja, SMS obvestila, Google ocene in akcije — brez sestavljanja različnih orodij." secondary={{label:"Poglejte cenik",href:"/cenik"}}><BrowserFrame><div className="aspect-video bg-[#EDE8F8]"><PromoVideoPlayer/></div></BrowserFrame></MarketingHero>
  <section className="border-y border-[#ECEAF2] bg-white px-5 py-8 md:px-8"><div className="mx-auto flex max-w-[950px] flex-wrap justify-center gap-x-8 gap-y-3 text-[13px] font-bold text-[#55515E]">{["Spletna stran","Povpraševanja","SMS obvestila","Google ocene","Akcije","Podpora"].map(x=><span key={x} className="flex items-center gap-2"><Check size={14} className="text-[#219A6B]"/>{x}</span>)}</div></section>
  <section className="px-5 py-24 md:px-8 md:py-28"><div className="mx-auto max-w-[1120px]"><MarketingHeading eyebrow="Vključeno v naročnino" title="Vse, kar potrebujete od prvega obiska do naslednje stranke." text="Vsak del sistema je povezan in ga za vas postavi ter vzdržuje ista ekipa."/><div className="mt-14 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{services.map(([Icon,t,d,items])=>{const I=Icon as typeof Globe2;return <article key={t as string} className="rounded-[24px] border border-[#E8E5EE] bg-[#FCFBFD] p-7"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-[#EEEAFE] text-[#6654DB]"><I size={22}/></span><h2 className="mt-6 text-xl font-extrabold tracking-[-.02em]">{t as string}</h2><p className="mt-3 text-sm leading-6 text-[#696470]">{d as string}</p><div className="mt-6 space-y-2.5 border-t border-[#EDEAF1] pt-5">{(items as string[]).map(x=><div key={x} className="flex items-center gap-2 text-xs font-bold text-[#55515E]"><Check size={13} className="text-[#219A6B]"/>{x}</div>)}</div></article>})}</div></div></section>
  <section className="bg-[#17141F] px-5 py-24 text-white md:px-8 md:py-28"><div className="mx-auto grid max-w-[1060px] items-center gap-14 lg:grid-cols-[.9fr_1.1fr]"><div><div className="text-xs font-extrabold uppercase tracking-[.13em] text-[#B9B0FF]">Ena naročnina</div><h2 className="mt-4 text-balance text-[36px] font-extrabold leading-[1.12] tracking-[-.038em] md:text-[48px]">Vi opravljate delo. Mi skrbimo za sistem.</h2><p className="mt-5 text-[16px] leading-7 text-[#AAA5B4]">Vsebina, gostovanje, spremembe in podpora so vključeni. Če potrebujete novo fotografijo, besedilo ali podstran, zahtevek oddate ekipi.</p><Button asChild variant="inverse" className="mt-7"><Link href="/kontakt">Brezplačen posvet <ArrowRight size={17}/></Link></Button></div><div className="rounded-[26px] border border-white/10 bg-white/5 p-7"><div className="text-xs font-bold uppercase tracking-wider text-[#8F8998]">Osnovni paket</div><div className="mt-3 flex items-end gap-2"><span className="text-[56px] font-extrabold tracking-[-.05em]">99 €</span><span className="pb-2 text-sm text-[#AAA5B4]">/ mesec</span></div><div className="mt-6 grid gap-3 sm:grid-cols-2">{["Brez vezave","Brez začetnega stroška","Postavitev vključena","Podpora vključena","Gostovanje vključeno","Prekinitev kadarkoli"].map(x=><div key={x} className="flex gap-2 text-sm font-semibold"><Check size={15} className="mt-0.5 text-[#AFA4FF]"/>{x}</div>)}</div></div></div></section>
  <section className="bg-[#F7F5FC] px-5 py-24 md:px-8 md:py-28"><div className="mx-auto max-w-[1100px]"><MarketingHeading eyebrow="Dodatne storitve" title="Dodajte več vidnosti, ko ste pripravljeni." text="Osnovni sistem lahko nadgradite z lokalnim profilom, SEO optimizacijo ali oglaševanjem."/><div className="mt-12"><AddonPricingCards items={addons} columns="three"/></div></div></section><CtaBand title="En sistem. Ena ekipa. Več priložnosti." text="Začnite z brezplačnim 20-minutnim pogovorom o vašem podjetju in ciljih."/></main></PageShell>}
