import Link from "next/link";
import { ArrowRight, BellRing, Check, MailCheck, MessageSquareText, Rocket, Settings2 } from "lucide-react";

import { FaqAccordion } from "@/components/faq-accordion";
import { BrowserFrame, MarketingHeading, MarketingHero } from "@/components/premium-marketing";
import { PromoVideoPlayer } from "@/components/promo-video-player";
import { CtaBand, PageShell } from "@/components/site-shell";
import { Button } from "@/components/ui/button";
import { createMetadata } from "@/lib/seo";

export const metadata = createMetadata({ title: "How Obrtio works", description: "From a free call to a complete website and lead system in 7–10 days.", path: "/how-it-works", locale: "en_US", languages: { en: "/how-it-works", "sl-SI": "/kako-deluje", "x-default": "/how-it-works" } });

const setup = ["Website copy and structure", "Mobile-friendly design", "Contact forms", "SMS and email notifications", "Hosting and maintenance", "Dashboard setup"];
const faqs = [{ q: "How long does setup take?", a: "Most websites and customer systems are ready within 7–10 days once we have the basics about your business." }, { q: "Do I need technical knowledge?", a: "No. We handle setup, hosting, maintenance and technical details for you." }, { q: "What happens when a customer sends an inquiry?", a: "You receive an SMS alert, the customer receives an email confirmation and the inquiry is saved in your dashboard." }];

export default function HowItWorksPage() { return <PageShell active="kako" locale="en"><main><MarketingHero locale="en" eyebrow="How it works" title="From the first call to a system that" highlight="works for you." text="We build the website, connect notifications and prepare the content. You get a clear view of new customers and stay focused on your work." secondary={{ label: "See the inquiry flow", href: "#flow" }}><BrowserFrame label="app.obrtio.com"><div className="aspect-video bg-[#EDE8F8]"><PromoVideoPlayer /></div></BrowserFrame></MarketingHero>
  <section className="px-5 py-24 md:px-8 md:py-28"><div className="mx-auto max-w-[1080px]"><MarketingHeading eyebrow="Setup" title="Three clear stages. No technical work for you." /><div className="relative mt-14 grid gap-5 md:grid-cols-3">{[[MessageSquareText, "01", "We learn about your business", "On a short call, we collect your services, service area, references and goals."], [Settings2, "02", "We build everything", "We prepare the copy, website, forms, SMS alerts and your account."], [Rocket, "03", "You start receiving inquiries", "Once approved, we publish the website and the system begins collecting inquiries."]].map(([Icon, number, title, description]) => { const I = Icon as typeof Rocket; return <article key={number as string} className="rounded-[24px] border border-[#E8E5EE] bg-white p-8 shadow-[0_12px_35px_rgba(28,23,46,.05)]"><div className="flex items-center justify-between"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-[#EEEAFE] text-[#6654DB]"><I size={20} /></span><span className="font-mono text-xs font-bold text-[#A09BA8]">{number as string}</span></div><h3 className="mt-7 text-xl font-extrabold">{title as string}</h3><p className="mt-3 text-sm leading-6 text-[#696470]">{description as string}</p></article> })}</div><div className="mt-8 text-center text-sm font-bold text-[#6654DB]">Usually ready in 7–10 days</div></div></section>
  <section id="flow" className="bg-[#17141F] px-5 py-24 text-white md:px-8 md:py-28"><div className="mx-auto max-w-[1080px]"><MarketingHeading eyebrow="Inquiry flow" title="Every customer gets a response. You get notified." text="The system handles the first response before you can pick up the phone." align="left" /><div className="mt-14 grid gap-4 lg:grid-cols-4">{[[MessageSquareText, "1. Form submitted", "The customer clearly explains what they need."], [MailCheck, "2. Customer confirmation", "They receive a professional email immediately."], [BellRing, "3. SMS to contractor", "You are notified about the new inquiry right away."], [Check, "4. Saved in the system", "The contact and message are ready for your response."]].map(([Icon, title, description]) => { const I = Icon as typeof Check; return <article key={title as string} className="rounded-[20px] border border-white/10 bg-white/5 p-6"><I size={20} className="text-[#B9B0FF]" /><h3 className="mt-5 text-sm font-extrabold">{title as string}</h3><p className="mt-2 text-xs leading-5 text-[#AAA5B4]">{description as string}</p></article> })}</div></div></section>
  <section className="px-5 py-24 md:px-8 md:py-28"><div className="mx-auto grid max-w-[1050px] items-center gap-14 lg:grid-cols-2"><div><MarketingHeading eyebrow="Setup included" title="What we handle for you." text="We only need the basics about your business. The Obrtio team takes care of everything else." align="left" /><Button asChild className="mt-7"><Link href="/contact">Start the conversation <ArrowRight size={17} /></Link></Button></div><div className="grid gap-3 sm:grid-cols-2">{setup.map(item => <div key={item} className="flex gap-3 rounded-xl border border-[#E9E7EF] bg-[#FCFBFD] p-4 text-sm font-bold"><span className="grid h-6 w-6 shrink-0 place-items-center rounded-lg bg-[#6654DB] text-white"><Check size={12} /></span>{item}</div>)}</div></div></section>
  <section className="bg-[#F7F5FC] px-5 py-24 md:px-8"><div className="mx-auto max-w-[760px]"><MarketingHeading eyebrow="Frequently asked questions" title="Good to know before we start." /><div className="mt-10"><FaqAccordion items={faqs} /></div></div></section><CtaBand locale="en" title="The first step takes just 20 minutes" text="Tell us how you currently win customers. We will show you a clear next step." /></main></PageShell>; }
