import { Check, HelpCircle, ShieldCheck, Sparkles } from "lucide-react";

import { AddonPricingCards } from "@/components/addon-pricing-cards";
import { FaqAccordion } from "@/components/faq-accordion";
import { MarketingHeading, MarketingHero } from "@/components/premium-marketing";
import { PricingSwitcher } from "@/components/pricing-switcher";
import { CtaBand, PageShell } from "@/components/site-shell";
import { createMetadata } from "@/lib/seo";

export const metadata = createMetadata({ title: "Pricing — contractor growth system from $199", description: "Website, lead management, SMS alerts, Google reviews, campaigns, hosting and support for $199 per month or $1,900 per year.", path: "/pricing", locale: "en_US", languages: { en: "/pricing", "sl-SI": "/cenik", "x-default": "/pricing" } });

const addons = [{ title: "AI Assistant", price: "Coming soon", unit: "", features: ["Message summaries", "Quote drafts", "Always with your approval"] }, { title: "Google Business Profile", price: "$500", unit: "one-time", features: ["Profile setup", "Category optimization", "Stronger local presence"] }, { title: "SEO", price: "$500", unit: "one-time", features: ["Local SEO", "Technical improvements", "Key content"] }, { title: "Advertising", price: "Custom quote", unit: "campaigns", features: ["Google Ads", "Meta and TikTok", "Image ads"] }];
const faqs = [{ q: "Is there a setup fee?", a: "No. Setup is included in your subscription." }, { q: "Can I cancel at any time?", a: "Yes. There is no contract and no cancellation penalty." }, { q: "What is included?", a: "Your website, hosting, maintenance, inquiry management, SMS alerts, review requests, campaigns and support." }];

export default function PricingPage() { return <PageShell active="cenik" locale="en"><main><MarketingHero locale="en" eyebrow="Simple pricing" title="One plan. Everything you need." highlight="No surprises." text="A website, inquiry system, SMS alerts, Google reviews, campaigns and support in one clear subscription." secondary={{ label: "What is included", href: "#included" }} />
  <section id="included" className="px-5 pb-24 md:px-8 md:pb-28"><PricingSwitcher locale="en" /></section>
  <section className="bg-[#17141F] px-5 py-20 text-white md:px-8"><div className="mx-auto grid max-w-[1050px] gap-10 md:grid-cols-[.8fr_1.2fr]"><div><div className="text-xs font-extrabold uppercase tracking-[.13em] text-[#B9B0FF]">Clear terms</div><h2 className="mt-4 text-[34px] font-extrabold leading-tight tracking-[-.035em]">You only pay while you use the system.</h2></div><div className="grid gap-4 sm:grid-cols-3">{[[ShieldCheck, "No contract", "Cancel anytime."], [Check, "No setup fee", "Setup is included."], [Sparkles, "Fully managed", "Our team handles hosting and updates."]].map(([Icon, title, description]) => { const I = Icon as typeof Check; return <article key={title as string} className="rounded-2xl border border-white/10 bg-white/5 p-5"><I size={20} className="text-[#B9B0FF]" /><h3 className="mt-4 text-sm font-extrabold">{title as string}</h3><p className="mt-1 text-xs leading-5 text-[#AAA5B4]">{description as string}</p></article> })}</div></div></section>
  <section className="bg-[#F7F5FC] px-5 py-24 md:px-8 md:py-28"><div className="mx-auto max-w-[1080px]"><MarketingHeading eyebrow="Optional services" title="Upgrade only when you need it." text="The core plan already covers your website and customer system. Add services based on your goals." /><div className="mt-12"><AddonPricingCards items={addons} locale="en" /></div></div></section>
  <section className="px-5 py-24 md:px-8 md:py-28"><div className="mx-auto max-w-[760px]"><div className="flex justify-center"><HelpCircle className="text-[#6654DB]" /></div><MarketingHeading eyebrow="Frequently asked questions" title="Everything about pricing and terms." /><div className="mt-10"><FaqAccordion items={faqs} /></div></div></section><CtaBand locale="en" title="Start without a large upfront cost" text="$199 per month or $1,900 per year. No contract or hidden fees." /></main></PageShell>; }
