import Link from "next/link";
import { ArrowRight, BellRing, Check, Globe2, LifeBuoy, MessageSquareText, Send, Star } from "lucide-react";

import { AddonPricingCards } from "@/components/addon-pricing-cards";
import { BrowserFrame, MarketingHeading, MarketingHero } from "@/components/premium-marketing";
import { PromoVideoPlayer } from "@/components/promo-video-player";
import { CtaBand, PageShell } from "@/components/site-shell";
import { Button } from "@/components/ui/button";
import { createMetadata } from "@/lib/seo";

export const metadata = createMetadata({ title: "Website, leads and reviews for contractors", description: "A managed website, instant lead alerts, customer tracking, Google reviews and campaigns in one system.", path: "/services", locale: "en_US", languages: { en: "/services", "sl-SI": "/storitve", "x-default": "/services" } });

const services = [[Globe2, "Professional website", "Up to five pages tailored to your services, location and customers.", ["Copy and images", "Mobile-ready design", "Hosting and maintenance"]], [MessageSquareText, "Inquiries and customers", "Every new contact is saved in a clear system ready for your response.", ["Contact forms", "Statuses and notes", "Customer overview"]], [BellRing, "Instant notifications", "You receive an SMS when an inquiry arrives, while the customer gets an email confirmation.", ["SMS to contractor", "Customer confirmation", "Fewer missed opportunities"]], [Star, "Google reviews", "After the job, send a friendly Google review request in a few clicks.", ["SMS requests", "Private feedback", "More trust"]], [Send, "Campaigns and referrals", "Re-engage past customers and encourage referrals.", ["Marketing campaigns", "Referral campaigns", "Results overview"]], [LifeBuoy, "A fully managed system", "You do not need to manage the website, hosting or technical setup.", ["Content updates", "Technical support", "Ongoing maintenance"]]];
const addons = [{ title: "AI Assistant", price: "Coming soon", unit: "", features: ["Message summaries", "Quote drafts", "Always with your approval"] }, { title: "Google Business Profile", price: "$500", unit: "one-time", features: ["Profile setup", "Category optimization", "A stronger local presence"] }, { title: "SEO", price: "$500", unit: "one-time", features: ["Local SEO", "Technical improvements", "Key content"] }, { title: "Advertising", price: "Custom quote", unit: "campaigns", features: ["Google Ads", "Meta and TikTok", "Image ads"] }];

export default function ServicesPage() { return <PageShell active="storitve" locale="en"><main><MarketingHero locale="en" eyebrow="Everything in one system" title="More than a website." highlight="A customer system." text="Obrtio connects your professional online presence, inquiries, SMS alerts, Google reviews and campaigns — without a stack of disconnected tools." secondary={{ label: "See pricing", href: "/pricing" }}><BrowserFrame label="app.obrtio.com"><div className="aspect-video bg-[#EDE8F8]"><PromoVideoPlayer /></div></BrowserFrame></MarketingHero>
  <section className="border-y border-[#ECEAF2] bg-white px-5 py-8 md:px-8"><div className="mx-auto flex max-w-[950px] flex-wrap justify-center gap-x-8 gap-y-3 text-[13px] font-bold text-[#55515E]">{["Website", "Inquiries", "SMS alerts", "Google reviews", "Campaigns", "Support"].map(x => <span key={x} className="flex items-center gap-2"><Check size={14} className="text-[#219A6B]" />{x}</span>)}</div></section>
  <section className="px-5 py-24 md:px-8 md:py-28"><div className="mx-auto max-w-[1120px]"><MarketingHeading eyebrow="Included in your subscription" title="Everything you need from the first visit to the next customer." text="Every part of the system is connected, built and maintained by the same team." /><div className="mt-14 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{services.map(([Icon, title, description, items]) => { const I = Icon as typeof Globe2; return <article key={title as string} className="rounded-[24px] border border-[#E8E5EE] bg-[#FCFBFD] p-7"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-[#EEEAFE] text-[#6654DB]"><I size={22} /></span><h2 className="mt-6 text-xl font-extrabold tracking-[-.02em]">{title as string}</h2><p className="mt-3 text-sm leading-6 text-[#696470]">{description as string}</p><div className="mt-6 space-y-2.5 border-t border-[#EDEAF1] pt-5">{(items as string[]).map(item => <div key={item} className="flex items-center gap-2 text-xs font-bold text-[#55515E]"><Check size={13} className="text-[#219A6B]" />{item}</div>)}</div></article> })}</div></div></section>
  <section className="bg-[#17141F] px-5 py-24 text-white md:px-8 md:py-28"><div className="mx-auto grid max-w-[1060px] items-center gap-14 lg:grid-cols-[.9fr_1.1fr]"><div><div className="text-xs font-extrabold uppercase tracking-[.13em] text-[#B9B0FF]">One subscription</div><h2 className="mt-4 text-balance text-[36px] font-extrabold leading-[1.12] tracking-[-.038em] md:text-[48px]">You do the work. We run the system.</h2><p className="mt-5 text-[16px] leading-7 text-[#AAA5B4]">Copy, hosting, updates and support are included. When you need a new photo, page or piece of text, you send a request to our team.</p><Button asChild variant="inverse" className="mt-7"><Link href="/contact">Book a free call <ArrowRight size={17} /></Link></Button></div><div className="rounded-[26px] border border-white/10 bg-white/5 p-7"><div className="text-xs font-bold uppercase tracking-wider text-[#8F8998]">Core plan</div><div className="mt-3 flex items-end gap-2"><span className="text-[56px] font-extrabold tracking-[-.05em]">$199</span><span className="pb-2 text-sm text-[#AAA5B4]">/ month</span></div><div className="mt-6 grid gap-3 sm:grid-cols-2">{["No contract", "No setup fee", "Setup included", "Support included", "Hosting included", "Cancel anytime"].map(x => <div key={x} className="flex gap-2 text-sm font-semibold"><Check size={15} className="mt-0.5 text-[#AFA4FF]" />{x}</div>)}</div></div></div></section>
  <section className="bg-[#F7F5FC] px-5 py-24 md:px-8 md:py-28"><div className="mx-auto max-w-[1100px]"><MarketingHeading eyebrow="Optional services" title="Add more visibility when you are ready." text="Enhance the core system with a local profile, SEO or advertising." /><div className="mt-12"><AddonPricingCards items={addons} columns="three" locale="en" /></div></div></section><CtaBand locale="en" title="One system. One team. More opportunities." text="Start with a free 20-minute conversation about your business and goals." /></main></PageShell>; }
